#!/usr/bin/env bash
# Nexus Memory System installer (Rust-first, user-level)

set -euo pipefail
IFS=$'\n\t'

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info() { echo -e "${BLUE}[INFO]${NC} $1"; }
ok() { echo -e "${GREEN}[OK]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
err() { echo -e "${RED}[ERROR]${NC} $1"; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

BIN_DIR="${NEXUS_INSTALL_BIN_DIR:-${HOME}/.local/bin}"
CONFIG_DIR="${NEXUS_INSTALL_CONFIG_DIR:-${XDG_CONFIG_HOME:-${HOME}/.config}/nexus-memory-system}"
DATA_DIR="${NEXUS_INSTALL_DATA_DIR:-${XDG_DATA_HOME:-${HOME}/.local/share}/nexus-memory-system}"
STATE_DIR="${NEXUS_INSTALL_STATE_DIR:-${XDG_STATE_HOME:-${HOME}/.local/state}/nexus-memory-system}"
DB_PATH="${NEXUS_DATABASE_PATH:-${DATA_DIR}/nexus.db}"
ENV_FILE="${CONFIG_DIR}/nexus.env"
FISH_ENV_FILE="${CONFIG_DIR}/nexus.fish"

BINARY_PATH=""
PROFILE_FILE=""
SKIP_PROFILE=0

usage() {
    cat <<EOF
Usage: $0 [options]

Options:
  --binary PATH         Path to compiled nexus binary
  --bin-dir DIR         Install directory for executables (default: ${BIN_DIR})
  --config-dir DIR      Config directory (default: ${CONFIG_DIR})
  --data-dir DIR        Data directory (default: ${DATA_DIR})
  --state-dir DIR       State/log directory (default: ${STATE_DIR})
  --db-path PATH        Shared Nexus database path (default: ${DB_PATH})
  --profile FILE        Shell profile to update (.bashrc/.zshrc/config.fish)
  --skip-profile        Do not modify shell profile
  -h, --help            Show this help
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --binary)
            BINARY_PATH="$2"
            shift 2
            ;;
        --bin-dir)
            BIN_DIR="$2"
            shift 2
            ;;
        --config-dir)
            CONFIG_DIR="$2"
            ENV_FILE="${CONFIG_DIR}/nexus.env"
            FISH_ENV_FILE="${CONFIG_DIR}/nexus.fish"
            shift 2
            ;;
        --data-dir)
            DATA_DIR="$2"
            DB_PATH="${DATA_DIR}/nexus.db"
            shift 2
            ;;
        --state-dir)
            STATE_DIR="$2"
            shift 2
            ;;
        --db-path)
            DB_PATH="$2"
            shift 2
            ;;
        --profile)
            PROFILE_FILE="$2"
            shift 2
            ;;
        --skip-profile)
            SKIP_PROFILE=1
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            err "Unknown argument: $1"
            usage
            exit 1
            ;;
    esac
done

resolve_binary() {
    if [[ -n "${BINARY_PATH}" ]]; then
        return
    fi

    if [[ -x "${REPO_ROOT}/target/release/nexus" ]]; then
        BINARY_PATH="${REPO_ROOT}/target/release/nexus"
        return
    fi

    if command -v nexus-bin >/dev/null 2>&1; then
        BINARY_PATH="$(command -v nexus-bin)"
        return
    fi

    if command -v nexus >/dev/null 2>&1; then
        BINARY_PATH="$(command -v nexus)"
        return
    fi

    err "Could not find a nexus binary. Build first with: cargo build --release -p nexus-cli"
    exit 1
}

write_env_file() {
    mkdir -p "${CONFIG_DIR}"

    cat > "${ENV_FILE}" <<EOF
# Generated by scripts/install.sh
export NEXUS_DATABASE_PATH="${DB_PATH}"
export NEXUS_SYNC_POLICY="auto"
export NEXUS_AUTO_INGEST="true"
export NEXUS_EMBEDDINGS_ENABLED="true"
EOF

    cat > "${FISH_ENV_FILE}" <<EOF
# Generated by scripts/install.sh
set -gx NEXUS_DATABASE_PATH "${DB_PATH}"
set -gx NEXUS_SYNC_POLICY "auto"
set -gx NEXUS_AUTO_INGEST "true"
set -gx NEXUS_EMBEDDINGS_ENABLED "true"
if not contains -- "${BIN_DIR}" \$PATH
    set -gx PATH "${BIN_DIR}" \$PATH
end
EOF

    ok "Wrote shared environment files"
}

install_nexus_binaries() {
    mkdir -p "${BIN_DIR}"

    install -m 0755 "${BINARY_PATH}" "${BIN_DIR}/nexus-bin"

    cat > "${BIN_DIR}/nexus" <<EOF
#!/usr/bin/env bash
set -euo pipefail
if [[ -f "${ENV_FILE}" ]]; then
  . "${ENV_FILE}"
fi
exec "${BIN_DIR}/nexus-bin" "\$@"
EOF
    chmod +x "${BIN_DIR}/nexus"

    cat > "${BIN_DIR}/nexus-with" <<EOF
#!/usr/bin/env bash
set -euo pipefail
if [[ -f "${ENV_FILE}" ]]; then
  . "${ENV_FILE}"
fi
if [[ \$# -eq 0 ]]; then
  echo "Usage: nexus-with <command> [args...]" >&2
  exit 1
fi
exec "\$@"
EOF
    chmod +x "${BIN_DIR}/nexus-with"

    ok "Installed nexus launchers to ${BIN_DIR}"
}

install_tool_wrappers() {
    local tools=(
        codex
        claude
        claude-code
        gemini
        qwen
        amp
        droid
        opencode
    )
    local installed=0

    for tool in "${tools[@]}"; do
        if command -v "${tool}" >/dev/null 2>&1; then
            cat > "${BIN_DIR}/${tool}-nexus" <<EOF
#!/usr/bin/env bash
set -euo pipefail
exec "${BIN_DIR}/nexus-with" "${tool}" "\$@"
EOF
            chmod +x "${BIN_DIR}/${tool}-nexus"
            installed=$((installed + 1))
        fi
    done

    if [[ ${installed} -gt 0 ]]; then
        ok "Installed ${installed} tool wrapper(s)"
    else
        warn "No known AI CLIs found in PATH for wrapper generation"
    fi
}

upsert_profile_block_posix() {
    local profile="$1"
    local begin="# >>> nexus-memory-system >>>"
    local end="# <<< nexus-memory-system <<<"

    mkdir -p "$(dirname "${profile}")"
    touch "${profile}"

    if grep -Fq "${begin}" "${profile}"; then
        ok "Profile already configured: ${profile}"
        return
    fi

    cat >> "${profile}" <<EOF

${begin}
if [ -f "${ENV_FILE}" ]; then
  . "${ENV_FILE}"
fi
case ":\$PATH:" in
  *:"${BIN_DIR}":*) ;;
  *) export PATH="${BIN_DIR}:\$PATH" ;;
esac
${end}
EOF

    ok "Updated profile: ${profile}"
}

upsert_profile_block_fish() {
    local profile="$1"
    local begin="# >>> nexus-memory-system >>>"
    local end="# <<< nexus-memory-system <<<"

    mkdir -p "$(dirname "${profile}")"
    touch "${profile}"

    if grep -Fq "${begin}" "${profile}"; then
        ok "Fish profile already configured: ${profile}"
        return
    fi

    cat >> "${profile}" <<EOF

${begin}
if test -f "${FISH_ENV_FILE}"
    source "${FISH_ENV_FILE}"
end
${end}
EOF

    ok "Updated fish profile: ${profile}"
}

configure_profiles() {
    if [[ ${SKIP_PROFILE} -eq 1 ]]; then
        warn "Skipping shell profile updates"
        return
    fi

    if [[ -n "${PROFILE_FILE}" ]]; then
        case "${PROFILE_FILE}" in
            *.fish) upsert_profile_block_fish "${PROFILE_FILE}" ;;
            *) upsert_profile_block_posix "${PROFILE_FILE}" ;;
        esac
        return
    fi

    if [[ -n "${BASH_VERSION:-}" ]]; then
        upsert_profile_block_posix "${HOME}/.bashrc"
    fi

    if [[ -f "${HOME}/.zshrc" ]]; then
        upsert_profile_block_posix "${HOME}/.zshrc"
    fi

    if [[ -d "${HOME}/.config/fish" ]]; then
        upsert_profile_block_fish "${HOME}/.config/fish/config.fish"
    fi
}

initialize_database() {
    mkdir -p "${DATA_DIR}" "${STATE_DIR}"
    if [[ -f "${ENV_FILE}" ]]; then
        . "${ENV_FILE}"
    fi
    "${BIN_DIR}/nexus" init
    ok "Initialized database at ${DB_PATH}"
}

# Ensure Claude Code's settings.json includes Nexus env vars so hooks
# inherit them even when the parent shell doesn't source nexus.env.
configure_claude_code() {
    local settings_file="${HOME}/.claude/settings.json"
    if [[ ! -f "${settings_file}" ]]; then
        warn "Claude Code settings not found at ${settings_file}"
        return
    fi

    # Check if NEXUS_DATABASE_PATH is already present in the env block
    if python3 -c "
import json, sys
with open('${settings_file}') as f:
    s = json.load(f)
env = s.get('env', {})
if env.get('NEXUS_DATABASE_PATH'):
    sys.exit(0)
sys.exit(1)
" 2>/dev/null; then
        ok "Claude Code settings.json already has Nexus env vars"
        return
    fi

    # Add Nexus env vars to the existing env block
    python3 -c "
import json

settings_path = '${settings_file}'
db_path = '${DB_PATH}'

with open(settings_path) as f:
    s = json.load(f)

if 'env' not in s:
    s['env'] = {}

s['env']['NEXUS_DATABASE_PATH'] = db_path
s['env']['NEXUS_SYNC_POLICY'] = 'auto'
s['env']['NEXUS_AUTO_INGEST'] = 'true'
s['env']['NEXUS_EMBEDDINGS_ENABLED'] = 'true'

with open(settings_path, 'w') as f:
    json.dump(s, f, indent=2)
    f.write('\n')
" 2>/dev/null

    if [[ $? -eq 0 ]]; then
        ok "Added Nexus env vars to Claude Code settings.json"
    else
        warn "Failed to update Claude Code settings.json (python3 required)"
    fi
}

main() {
    resolve_binary
    write_env_file
    install_nexus_binaries
    install_tool_wrappers
    configure_profiles
    initialize_database
    configure_claude_code

    echo
    ok "Nexus Memory System installation complete"
    echo "  Binary: ${BIN_DIR}/nexus"
    echo "  Database: ${DB_PATH}"
    echo "  Config: ${ENV_FILE}"
}

main "$@"
